const FONTES = [
  {nome:'InfoMoney',url:'https://www.infomoney.com.br/feed/'},{nome:'Money Times',url:'https://www.moneytimes.com.br/feed/'},{nome:'Suno',url:'https://www.suno.com.br/noticias/feed/'},{nome:'Exame',url:'https://exame.com/feed/'},{nome:'Exame Invest',url:'https://exame.com/invest/feed/'},{nome:'CNN Brasil',url:'https://www.cnnbrasil.com.br/economia/feed/'},{nome:'Investing.com',url:'https://br.investing.com/rss/news.rss'},{nome:'Valor Econômico',url:'https://valor.globo.com/rss/financas/index.xml'},{nome:'Bloomberg Línea',url:'https://www.bloomberglinea.com.br/feed/'},{nome:'Reuters Brasil',url:'https://br.reuters.com/rssFeed/businessNews'},{nome:'G1 Economia',url:'https://g1.globo.com/rss/g1/economia/'}
];
const RELEVANTES=['mercado','bolsa','ibovespa','ação','ações','b3','dólar','juros','selic','inflação','ipca','pib','economia','investimento','investidor','fundo','fii','dividendo','bitcoin','cripto','wall street','nasdaq','s&p','petrobras','vale','itaú','fed','tesouro','câmbio','commodities','lucro','balanço','copom','renda fixa','petróleo','ouro','minério','emprego','crédito','banco','fintech','pix','fiscal','tarifa','nvidia','tesla','apple'];
const EXCLUIDAS=['lotofácil','mega-sena','quina','loteria','horóscopo','novela','celebridade','famosos'];
const ALTO=['selic','copom','fed','juros','inflação','ipca','pib','ibovespa','wall street','nasdaq','s&p','dólar','recessão','crise','guerra','sanção','tarifa','recorde','dispara','despenca','petrobras','vale','bitcoin','nvidia','ipo','fusão','aquisição'];
const MEDIO=['mercado','bolsa','ação','economia','dividendo','fii','fundo','etf','investimento','lucro','balanço','petróleo','ouro','commodities','emprego','varejo','banco','crédito'];
function entities(value){return String(value||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#(?:39|8217);/g,"'").replace(/&#8211;/g,'–').replace(/&#(\d+);/g,(_,code)=>String.fromCharCode(Number(code))).trim()}
function text(value){return entities(String(value||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' '))}
function corrigirTextoEditorial(value){return String(value||'').replace(/\bvolatileve\b/gi,'volatilidade').replace(/\s+The post[\s\S]*?appeared first on\s+[^.]+\.?/gi,'').replace(/\s+([,.;:!?])/g,'$1').replace(/\s{2,}/g,' ').trim()}
function tag(block,name){const match=new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i').exec(block);return match?entities(match[1]):''}
function normal(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function titulosSimilares(a,b){const pa=new Set(normal(a).split(' ').filter(word=>word.length>3)),pb=new Set(normal(b).split(' ').filter(word=>word.length>3));if(!pa.size||!pb.size)return false;let common=0;for(const word of pa)if(pb.has(word))common++;return common/Math.min(pa.size,pb.size)>=.7}
function pillars(content){const value=normal(content),result=[];if(/ibovespa|bolsa|acao|b3|dividendo/.test(value))result.push('bolsa');if(/selic|juros|inflacao|ipca|pib|fiscal|emprego/.test(value))result.push('macro');if(/fii|renda fixa|tesouro|fundo|etf/.test(value))result.push('investimentos');if(/bitcoin|cripto/.test(value))result.push('cripto');if(/wall street|nasdaq|china|europa|fed|s&p/.test(value))result.push('exterior');if(/petroleo|ouro|minerio|commodit/.test(value))result.push('commodities');return result.length?result:['mercado']}
function score(content,title){const value=normal(content);let points=0;for(const word of ALTO)if(value.includes(normal(word)))points+=10;for(const word of MEDIO)if(value.includes(normal(word)))points+=3;if(/urgente|alerta|recorde|dispara|despenca|surpreende/i.test(title))points+=15;return points}
function parseItems(xml,source){const blocks=xml.match(/<item\b[\s\S]*?<\/item>/gi)||xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[];return blocks.map(block=>{const title=corrigirTextoEditorial(text(tag(block,'title'))),descriptionRaw=tag(block,'description')||tag(block,'summary')||tag(block,'content'),description=corrigirTextoEditorial(text(descriptionRaw)).slice(0,400),link=tag(block,'link')||(/<link[^>]+href=["']([^"']+)/i.exec(block)||[])[1]||'',date=tag(block,'pubDate')||tag(block,'published')||tag(block,'updated'),categories=[...block.matchAll(/<category(?:\s[^>]*)?>([\s\S]*?)<\/category>/gi)].map(match=>text(match[1])),combined=`${title} ${description} ${categories.join(' ')}`,normalized=normal(combined),image=(/<media:(?:content|thumbnail)[^>]+url=["']([^"']+)/i.exec(block)||/<enclosure[^>]+url=["']([^"']+)["'][^>]+type=["']image/i.exec(block)||/<img[^>]+src=["']([^"']+)/i.exec(descriptionRaw)||[])[1]||null;if(!title||!/^https?:\/\//i.test(link)||EXCLUIDAS.some(word=>normalized.includes(normal(word)))||!RELEVANTES.some(word=>normalized.includes(normal(word))))return null;return {titulo:title,link:entities(link),descricao:description,categorias:categories,imagem:image?entities(image):null,fonte:source.nome,pubDate:date,publicadoEm:date?new Date(date).getTime()||0:0,peso:score(combined,title),pilares:pillars(combined)}}).filter(Boolean)}
async function fetchSource(source){try{const response=await fetch(source.url,{headers:{'user-agent':'Mozilla/5.0 BDI-Studio/1.0'},signal:AbortSignal.timeout(16000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return parseItems(await response.text(),source)}catch(error){console.error(`Radar: ${source.nome}: ${error.message}`);return[]}}
async function buscarNoticiasRadar(limit=120){const all=(await Promise.all(FONTES.map(fetchSource))).flat();for(let i=0;i<all.length;i++){let coverage=0;for(let j=0;j<all.length;j++)if(i!==j&&titulosSimilares(all[i].titulo,all[j].titulo))coverage++;all[i].peso+=coverage*8;if(all[i].publicadoEm){const hours=(Date.now()-all[i].publicadoEm)/3600000;if(hours>12)all[i].peso-=Math.floor(hours-12)*2}}all.sort((a,b)=>b.peso-a.peso||b.publicadoEm-a.publicadoEm);const unique=[];for(const item of all)if(!unique.some(existing=>titulosSimilares(existing.titulo,item.titulo)))unique.push(item);return unique.slice(0,limit)}
module.exports={buscarNoticiasRadar,titulosSimilares,parseItems,corrigirTextoEditorial};
