const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeUrl=value=>/^https?:\/\//i.test(String(value||''))?escapeHtml(value):'#';
const mediaUrl=(item,index=0)=>item?.link?`/api/news/media?link=${encodeURIComponent(item.link)}&index=${index}`:'';
let radar={updatedAt:null,items:[]};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function timeAgo(value){const time=new Date(value).getTime();if(!time)return 'horário não informado';const hours=Math.max(0,Math.round((Date.now()-time)/3600000));if(hours<1)return 'agora';if(hours<24)return `há ${hours}h`;return `há ${Math.round(hours/24)}d`}
function isUsed(item){return item.jaPublicada||item.usadaNoStudio}
function fillFilters(){const sources=[...new Set(radar.items.map(item=>item.fonte).filter(Boolean))].sort(),pillars=[...new Set(radar.items.flatMap(item=>item.pilares||[]))].sort();$('sourceFilter').innerHTML='<option value="">Todas as fontes</option>'+sources.map(value=>`<option>${escapeHtml(value)}</option>`).join('');$('pillarFilter').innerHTML='<option value="">Todos os temas</option>'+pillars.map(value=>`<option>${escapeHtml(value)}</option>`).join('');$('sourceCount').textContent=sources.length||'—'}
function render(){
  const query=$('newsSearch').value.trim().toLowerCase(),source=$('sourceFilter').value,pillar=$('pillarFilter').value,status=$('statusFilter').value,sort=$('sortNews').value;
  let items=radar.items.filter(item=>(!query||`${item.titulo} ${item.descricao} ${item.fonte} ${(item.pilares||[]).join(' ')}`.toLowerCase().includes(query))&&(!source||item.fonte===source)&&(!pillar||(item.pilares||[]).includes(pillar))&&(!status||(status==='used'?isUsed(item):!isUsed(item))));
  items.sort(sort==='recent'?(a,b)=>(b.publicadoEm||0)-(a.publicadoEm||0):(a,b)=>(b.peso||0)-(a.peso||0));
  $('totalNews').textContent=radar.items.length;$('unusedNews').textContent=radar.items.filter(item=>!isUsed(item)).length;
  $('newsGrid').innerHTML=items.length?items.map(item=>{const index=radar.items.indexOf(item),used=item.jaPublicada?'Bot já publicou':item.usadaNoStudio?'Usada no Studio':'',topic=item.pilares?.[0]||'Mercado';return `<article class="news-card"><div class="news-image"><div class="news-image-fallback"><small>BDI RADAR</small><strong>${escapeHtml(item.fonte||'Mercado')}</strong><span>${escapeHtml(topic)}</span></div>${item.link?`<img src="${mediaUrl(item)}" alt="Imagem editorial da matéria" loading="lazy" onerror="this.remove()">`:''}<span class="news-score">Impacto ${Number(item.peso||0)}</span></div><div class="news-body"><div class="news-meta"><b>${escapeHtml(item.fonte)}</b><span>•</span><span>${timeAgo(item.pubDate||item.publicadoEm)}</span>${used?`<span class="used">✓ ${used}</span>`:''}</div><h3>${escapeHtml(item.titulo)}</h3><p>${escapeHtml(item.descricao||'Abra a matéria para consultar todos os detalhes e confirmar o contexto.')}</p><div class="pillars">${(item.pilares||[]).map(value=>`<span class="pillar">${escapeHtml(value)}</span>`).join('')}</div><div class="news-actions"><button class="make-story" data-create="story" data-index="${index}">Criar Story</button><button class="make-post" data-create="carousel" data-index="${index}">Criar carrossel</button><button class="make-reel" data-create="reel" data-index="${index}">Criar Reel</button><a class="read-link" href="${safeUrl(item.link)}" target="_blank" rel="noopener noreferrer">Ler matéria original ↗</a></div></div></article>`}).join(''):'<div class="news-empty"><b>Nenhuma pauta encontrada.</b><span>Tente remover um filtro ou atualizar as notícias.</span></div>';
  document.querySelectorAll('[data-create]').forEach(button=>button.onclick=()=>createFromNews(radar.items[Number(button.dataset.index)],button.dataset.create));
}
async function loadNews(){try{const response=await fetch('/api/news');if(!response.ok)throw new Error();radar=await response.json();fillFilters();render();if(radar.updatedAt)$('updatedAt').textContent=`Última atualização: ${new Date(radar.updatedAt).toLocaleString('pt-BR')}`;if(!radar.items.length)await refreshNews()}catch{toast('Não foi possível abrir o radar agora')}}
async function refreshNews(){const button=$('refreshNews');button.disabled=true;button.textContent='Consultando as fontes…';document.body.classList.add('refreshing');try{const response=await fetch('/api/news/refresh',{method:'POST'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Falha na atualização');radar=data;fillFilters();render();$('updatedAt').textContent=radar.updatedAt?`Última atualização: ${new Date(radar.updatedAt).toLocaleString('pt-BR')}`:'Sem atualização recente';toast(radar.warning||`${radar.items.length} pautas encontradas`)}catch(error){toast(error.message||'As fontes não responderam agora')}finally{button.disabled=false;button.textContent='Atualizar notícias';document.body.classList.remove('refreshing')}}
async function createFromNews(item,format){
  const buttons=[...document.querySelectorAll(`[data-index="${radar.items.indexOf(item)}"]`)];buttons.forEach(button=>{button.disabled=true;button.dataset.originalText=button.textContent;button.textContent='Lendo matéria…'});
  let enriched={...item},sharedProject=null;
  try{const response=await fetch(`/api/news/article?link=${encodeURIComponent(item.link)}`),article=await response.json();if(response.ok){enriched={...item,conteudo:article.texto,blocos:article.blocos};sharedProject=article.projects?.[format]||null}}
  catch{}
  localStorage.setItem(format==='story'?'bdi-story-seed':'bdi-news-seed',JSON.stringify({item:enriched,format,project:sharedProject,createdAt:new Date().toISOString()}));
  fetch('/api/news/mark',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({link:item.link})}).catch(()=>{});location.href=format==='story'?'stories.html?origem=radar':'index.html?origem=radar'
}
$('openStudio').onclick=()=>location.href='index.html';$('refreshNews').onclick=refreshNews;['newsSearch','sourceFilter','pillarFilter','statusFilter','sortNews'].forEach(id=>$(id).addEventListener(id==='newsSearch'?'input':'change',render));loadNews();
