const $=id=>document.getElementById(id);
const defaultSlide=()=>({category:'Mercado agora',headline:'O dado que pode mudar o humor do mercado hoje',body:'Entenda o que aconteceu, por que isso importa e quais sinais o investidor deve acompanhar nas próximas horas.',source:'Bom Dia Investidor',imageCredit:'',cta:'Arraste para entender →',colorA:'#071d18',colorB:'#0c4b38',accent:'#d9aa43',image:'',duration:3});
let state={format:'feed',active:0,slides:[defaultSlide(),{...defaultSlide(),category:'O que aconteceu',headline:'O mercado recebeu um sinal importante',body:'O movimento ganhou força depois da divulgação do dado. Agora, investidores recalibram as expectativas.',cta:'Veja o impacto →'},{...defaultSlide(),category:'Para acompanhar',headline:'Três sinais para observar a partir de agora',body:'Juros, câmbio e o comportamento das bolsas globais ajudam a medir se o movimento terá continuidade.',cta:'Salve este resumo'}]};
const fields=['category','headline','bodyText','source','imageCredit','cta','colorA','colorB','accent'];
const keyMap={bodyText:'body'};
const current=()=>state.slides[state.active];
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const templates={
  news:{format:'carousel',caption:'Mercado em movimento: veja o que aconteceu e quais sinais acompanhar.\n\n📌 Salve para consultar depois.\n\nConteúdo informativo; não é recomendação de investimento.\n\n#mercadofinanceiro #investimentos #bomdiainvestidor',slides:[{category:'Mercado agora',headline:'A notícia que está movimentando os mercados',body:'Veja o fato, o contexto e o possível impacto para quem investe.',cta:'Arraste para entender →'},{category:'O que aconteceu',headline:'O mercado recebeu uma nova informação',body:'Explique o acontecimento com objetividade e deixe os números mais importantes em evidência.',cta:'Veja o impacto →'},{category:'No seu radar',headline:'O que o investidor deve acompanhar agora',body:'Liste os próximos indicadores, eventos e sinais sem transformar informação em recomendação.',cta:'Salve este resumo'}]},
  educational:{format:'carousel',caption:'Um conceito de investimentos explicado sem complicação.\n\nEnvie para alguém que também quer aprender.\n\nConteúdo informativo; não é recomendação de investimento.\n\n#educacaofinanceira #investimentos #bomdiainvestidor',slides:[{category:'Aprenda em 1 minuto',headline:'O que é este conceito e por que ele importa?',body:'Comece com uma definição simples, concreta e sem jargão.',cta:'Arraste para aprender →'},{category:'Na prática',headline:'Como isso aparece na vida do investidor',body:'Use um exemplo cotidiano ou uma comparação fácil de visualizar.',cta:'Veja um exemplo →'},{category:'Resumo',headline:'O essencial para você guardar',body:'Feche com três ideias curtas que ajudem o leitor a lembrar do conceito.',cta:'Salve para revisar'}]},
  closing:{format:'carousel',caption:'Fechamento do mercado: os movimentos que marcaram o dia.\n\n📊 Salve para acompanhar a evolução.\n\nConteúdo informativo; não é recomendação de investimento.\n\n#bolsa #mercadofinanceiro #bomdiainvestidor',slides:[{category:'Fechamento',headline:'Como o mercado terminou o dia',body:'Resuma o desempenho dos principais índices, juros, dólar e commodities.',cta:'Veja os destaques →'},{category:'Destaques do pregão',headline:'Os ativos que mais chamaram atenção',body:'Mostre altas, baixas e o contexto por trás dos movimentos relevantes.',cta:'Entenda os movimentos →'},{category:'Amanhã no radar',headline:'O que pode mexer com o próximo pregão',body:'Organize a agenda econômica e os eventos corporativos mais importantes.',cta:'Salve a agenda'}]},
  alert:{format:'feed',caption:'⚠️ Alerta de mercado. Entenda o movimento antes de tirar conclusões.\n\nConteúdo informativo; não é recomendação de investimento.\n\n#alertademercado #investimentos #bomdiainvestidor',slides:[{category:'Alerta de mercado',headline:'Movimento importante acontecendo agora',body:'Explique o que mudou, o tamanho do movimento e qual é a fonte da informação.',cta:'Leia o contexto completo'}]},
  reel:{format:'reel',caption:'O resumo que o investidor precisa para começar bem informado.\n\n▶️ Assista até o final e salve para rever.\n\nConteúdo informativo; não é recomendação de investimento.\n\n#reelsfinancas #mercadofinanceiro #bomdiainvestidor',slides:[{category:'Em 15 segundos',headline:'O principal movimento do mercado agora',body:'Abra com um fato forte e mostre por que ele merece atenção.',cta:'Continue assistindo',duration:3},{category:'O impacto',headline:'Por que isso importa para o investidor',body:'Conecte o acontecimento aos juros, câmbio, bolsa ou expectativas.',cta:'Veja o que acompanhar',duration:4},{category:'No radar',headline:'Os próximos sinais que merecem atenção',body:'Feche com informação útil, contexto e um convite para salvar.',cta:'Salve este Reel',duration:4}]}
};
let audioFile=null,narrationFile=null,audioMixSettings={musicVolume:.18,narrationVolume:1},previewToken=0,previewRunning=false,lastQueuedId=null,pendingQueueVideo=null,recoverQueueVideo=false,publishPoll=null;
const articleMediaUrl=(link,index=0)=>link?`/api/news/media?link=${encodeURIComponent(link)}&index=${index}`:'';
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function syncFields(){const s=current();fields.forEach(id=>$(id).value=s[keyMap[id]||id]||'')}
function render(){
  const s=current(),total=state.slides.length;
  $('previewCategory').textContent=s.category;$('previewHeadline').textContent=s.headline;$('previewBody').textContent=s.body;$('previewSource').textContent=s.source;$('previewImageCredit').textContent=s.imageCredit||'';$('previewCta').textContent=s.cta;$('slideCounter').textContent=total>1?`${state.active+1}/${total}`:'';
  $('art').style.setProperty('--accent',s.accent);$('art').style.background=s.image?`linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.72)),url("${s.image}") center/cover`:`linear-gradient(150deg,${s.colorA},${s.colorB} 70%,${s.colorA})`;
  const reel=state.format==='reel';document.body.classList.toggle('is-reel',reel);$('previewShell').classList.toggle('story',state.format==='story'||reel);$('captionMini').textContent=$('caption').value.slice(0,90);$('captionCount').textContent=`${$('caption').value.length}/2200`;$('sceneDuration').value=s.duration||3;$('durationValue').textContent=`${Number(s.duration||3).toLocaleString('pt-BR')}s`;$('exportAll').textContent=reel?'Gerar vídeo':'Exportar PNG';
  $('slides').innerHTML=state.slides.map((x,i)=>`<button class="slide-thumb ${i===state.active?'active':''}" data-slide="${i}" style="background:linear-gradient(150deg,${x.colorA},${x.colorB})">${i+1}. ${escapeHtml(x.headline)}${reel?` · ${x.duration||3}s`:''}</button>`).join('')+'<button class="addslide" id="addSlide" title="Adicionar slide">+</button>';
  document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{state.active=+b.dataset.slide;syncFields();render()});
  $('addSlide').onclick=()=>{state.slides.push({...defaultSlide(),category:'Novo slide',headline:'Escreva a próxima parte da história',body:'Use uma ideia por slide para manter a leitura simples e envolvente.'});state.active=state.slides.length-1;syncFields();render()};
}
fields.forEach(id=>$(id).addEventListener('input',e=>{current()[keyMap[id]||id]=e.target.value;render()}));
$('caption').addEventListener('input',render);
$('formatSelect').onchange=e=>{state.format=e.target.value;if(state.format==='reel')state.slides.forEach(s=>s.duration=s.duration||3);render()};
$('sceneDuration').oninput=e=>{current().duration=Number(e.target.value);render()};
$('imageUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,ratio=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);current().image=c.toDataURL('image/jpeg',.84);current().imageCredit='Imagem: acervo próprio';syncFields();render()};img.src=reader.result};reader.readAsDataURL(f)};
$('audioUpload').onchange=e=>{audioFile=e.target.files[0]||null;$('audioName').textContent=audioFile?audioFile.name:'Escolher música autorizada';$('removeAudio').style.display=audioFile?'block':'none';toast(audioFile?'Música adicionada ao Reel':'Nenhuma música selecionada')};
$('removeAudio').onclick=()=>{audioFile=null;$('audioUpload').value='';$('audioName').textContent='Escolher música autorizada';$('removeAudio').style.display='none';toast('Música removida')};
$('duplicateSlide').onclick=()=>{state.slides.splice(state.active+1,0,{...current()});state.active++;syncFields();render();toast('Slide duplicado')};
$('deleteSlide').onclick=()=>{if(state.slides.length===1)return toast('O projeto precisa de um slide');state.slides.splice(state.active,1);state.active=Math.max(0,state.active-1);syncFields();render()};
$('newProject').onclick=()=>{if(!confirm('Começar um projeto novo? O rascunho atual não salvo será perdido.'))return;previewToken++;audioFile=null;narrationFile=null;lastQueuedId=null;pendingQueueVideo=null;recoverQueueVideo=false;clearInterval(publishPoll);$('audioUpload').value='';$('audioName').textContent='Escolher música autorizada';$('approvePost').disabled=true;$('publishInstagram').disabled=true;$('queuePost').textContent='Enviar à fila local do bot';state={format:'feed',active:0,slides:[defaultSlide()]};$('formatSelect').value='feed';syncFields();render()};
document.querySelectorAll('[data-template]').forEach(button=>button.onclick=()=>{
  const preset=templates[button.dataset.template];
  if(!preset||!confirm('Aplicar este modelo e substituir o conteúdo atual?'))return;
  state={format:preset.format,active:0,slides:preset.slides.map(slide=>({...defaultSlide(),...slide}))};
  $('caption').value=preset.caption;$('formatSelect').value=state.format;syncFields();render();toast('Modelo aplicado');
});
function wrap(ctx,text,x,y,maxWidth,lineHeight,maxLines){const words=String(text).split(/\s+/);let line='',lines=[];for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines=lines.slice(0,maxLines);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return y+lines.length*lineHeight}
async function drawSlide(slide,index,thumb=false){
  const c=$('exportCanvas'),story=state.format==='story'||state.format==='reel';c.width=thumb?360:1080;c.height=thumb?450:(story?1920:1350);const ctx=c.getContext('2d'),scale=c.width/1080;ctx.save();ctx.scale(scale,scale);const W=1080,H=c.height/scale,g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,slide.colorA);g.addColorStop(.72,slide.colorB);g.addColorStop(1,slide.colorA);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  if(slide.image){await new Promise(resolve=>{const img=new Image();img.onload=()=>{const r=Math.max(W/img.width,H/img.height),w=img.width*r,h=img.height*r;ctx.drawImage(img,(W-w)/2,(H-h)/2,w,h);resolve()};img.onerror=resolve;img.src=slide.image});const ov=ctx.createLinearGradient(0,0,0,H);ov.addColorStop(0,'rgba(0,0,0,.08)');ov.addColorStop(1,'rgba(0,0,0,.76)');ctx.fillStyle=ov;ctx.fillRect(0,0,W,H)}
  ctx.font='900 25px Arial';const pill=Math.min(430,ctx.measureText(slide.category.toUpperCase()).width+80);ctx.fillStyle=slide.accent;ctx.beginPath();ctx.roundRect(72,72,pill,64,32);ctx.fill();ctx.fillStyle='#10130f';ctx.fillText(slide.category.toUpperCase(),105,114);ctx.fillStyle='white';ctx.font='900 76px Arial';ctx.textBaseline='top';const titleY=H-(story?820:540),contentWidth=story?840:920;let next=wrap(ctx,slide.headline,72,titleY,contentWidth,78,5);ctx.fillStyle='#e8eeeb';ctx.font='400 31px Arial';next=wrap(ctx,slide.body,72,next+28,contentWidth,43,4);const footerLineY=story?H-205:H-112,footerTextY=footerLineY+34,footerRight=story?930:1008;ctx.strokeStyle='rgba(255,255,255,.3)';ctx.beginPath();ctx.moveTo(72,footerLineY);ctx.lineTo(footerRight,footerLineY);ctx.stroke();ctx.font='800 23px Arial';ctx.fillStyle='white';ctx.fillText(slide.source,72,footerTextY);ctx.fillStyle=slide.accent;ctx.textAlign='right';ctx.fillText(slide.cta,footerRight,footerTextY);ctx.textAlign='left';
  if(slide.image&&slide.imageCredit){ctx.textAlign='left';ctx.font='700 17px Arial';const credit=String(slide.imageCredit).slice(0,80),creditWidth=Math.min(760,ctx.measureText(credit).width+34);ctx.fillStyle='rgba(0,0,0,.58)';ctx.beginPath();ctx.roundRect(72,153,creditWidth,38,8);ctx.fill();ctx.fillStyle='#f0f3f5';ctx.fillText(credit,89,164)}
  if(state.slides.length>1){ctx.fillStyle='rgba(0,0,0,.5)';ctx.beginPath();ctx.roundRect(908,72,100,48,24);ctx.fill();ctx.fillStyle='white';ctx.font='700 20px Arial';ctx.fillText(`${index+1}/${state.slides.length}`,937,86)}ctx.restore();return c;
}
function downloadCanvas(canvas,name){const a=document.createElement('a');a.download=name;a.href=canvas.toDataURL('image/png',.96);a.click()}
async function exportAll(){for(let i=0;i<state.slides.length;i++){const c=await drawSlide(state.slides[i],i);downloadCanvas(c,`bdi-${state.format}-slide-${i+1}.png`);await new Promise(r=>setTimeout(r,180))}toast(`${state.slides.length} PNG(s) exportado(s)`)}
$('exportAll').onclick=()=>state.format==='reel'?exportReel():exportAll();
function reelMime(){const options=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'];return options.find(type=>MediaRecorder.isTypeSupported(type))||''}
async function reelFrames(){const frames=[];for(let i=0;i<state.slides.length;i++){const canvas=await drawSlide(state.slides[i],i);frames.push(await createImageBitmap(canvas))}return frames}
async function createReelBlob(){
  if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw new Error('Este navegador não consegue gerar vídeo. Use Chrome ou Edge atualizado.');
  const total=state.slides.reduce((sum,slide)=>sum+Number(slide.duration||3),0);if(total>90)throw new Error('O Reel pode ter no máximo 90 segundos');
  const frames=await reelFrames(),canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext('2d'),videoStream=canvas.captureStream(30),tracks=[...videoStream.getVideoTracks()];let audioContext=null,destination=null,audioPlayers=[],audioUrls=[];
  if(audioFile||narrationFile){try{audioContext=new AudioContext();destination=audioContext.createMediaStreamDestination();const connect=async(file,volume,loop)=>{if(!file)return;const url=URL.createObjectURL(file),player=new Audio(url);player.loop=loop;const source=audioContext.createMediaElementSource(player),gain=audioContext.createGain();gain.gain.value=volume;source.connect(gain).connect(destination);audioPlayers.push(player);audioUrls.push(url);await player.play()};await connect(audioFile,audioMixSettings.musicVolume,true);await connect(narrationFile,audioMixSettings.narrationVolume,false);tracks.push(...destination.stream.getAudioTracks())}catch{toast('O áudio não pôde ser incorporado; o vídeo será gerado sem som')}}
  const stream=new MediaStream(tracks),mimeType=reelMime(),recorder=new MediaRecorder(stream,mimeType?{mimeType,videoBitsPerSecond:8_000_000}:undefined),chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
  const finished=new Promise((resolve,reject)=>{recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||mimeType||'video/webm'}));recorder.onerror=()=>reject(new Error('Falha ao gerar o arquivo de vídeo'))});
  recorder.start(500);const started=performance.now();
  await new Promise(resolve=>{function frame(now){const elapsed=Math.min(total,(now-started)/1000);let cursor=0,index=0;while(index<state.slides.length-1&&elapsed>=cursor+Number(state.slides[index].duration||3)){cursor+=Number(state.slides[index].duration||3);index++}const duration=Number(state.slides[index].duration||3),progress=Math.min(1,(elapsed-cursor)/duration),zoom=1+.025*progress,w=canvas.width*zoom,h=canvas.height*zoom;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(frames[index],(canvas.width-w)/2,(canvas.height-h)/2,w,h);if(progress>.84&&index<frames.length-1){ctx.globalAlpha=(progress-.84)/.16;ctx.drawImage(frames[index+1],0,0,canvas.width,canvas.height);ctx.globalAlpha=1}$('reelProgress').querySelector('i').style.width=`${Math.min(100,elapsed/total*100)}%`;$('reelTime').textContent=`${Math.ceil(total-elapsed)}s`;if(elapsed>=total)return resolve();requestAnimationFrame(frame)}requestAnimationFrame(frame)});
  recorder.stop();const blob=await finished;tracks.forEach(track=>track.stop());frames.forEach(frame=>frame.close());audioPlayers.forEach(player=>player.pause());audioUrls.forEach(url=>URL.revokeObjectURL(url));if(audioContext)await audioContext.close();$('reelProgress').querySelector('i').style.width='0';$('reelTime').textContent='0s';return blob;
}
function reelExtension(blob){return blob.type.includes('mp4')?'mp4':'webm'}
async function exportReel(){const button=$('exportAll'),old=button.textContent;button.disabled=true;button.textContent='Gravando Reel…';try{const blob=await createReelBlob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.download=`bdi-reel.${reelExtension(blob)}`;a.href=url;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast(`Reel exportado em ${reelExtension(blob).toUpperCase()}`);return blob}catch(error){toast(error.message||'Não foi possível gerar o Reel');return null}finally{button.disabled=false;button.textContent=old}}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
$('playReel').onclick=async()=>{const button=$('playReel');if(previewRunning){previewToken++;previewRunning=false;button.textContent='▶ Prévia do Reel';return}if(state.format!=='reel')return;previewRunning=true;const token=++previewToken,total=state.slides.reduce((sum,slide)=>sum+Number(slide.duration||3),0);button.textContent='■ Parar prévia';let elapsed=0;for(let i=0;i<state.slides.length&&token===previewToken;i++){state.active=i;syncFields();render();const phone=document.querySelector('.phone');phone.classList.remove('reel-playing');void phone.offsetWidth;phone.style.setProperty('--scene-duration',`${current().duration||3}s`);phone.classList.add('reel-playing');const duration=Number(current().duration||3),started=performance.now();while(token===previewToken&&(performance.now()-started)/1000<duration){const sceneElapsed=(performance.now()-started)/1000;$('reelProgress').querySelector('i').style.width=`${Math.min(100,(elapsed+sceneElapsed)/total*100)}%`;$('reelTime').textContent=`${Math.ceil(total-elapsed-sceneElapsed)}s`;await wait(60)}elapsed+=duration}previewToken++;previewRunning=false;document.querySelector('.phone').classList.remove('reel-playing');$('reelProgress').querySelector('i').style.width='0';$('reelTime').textContent='0s';button.textContent='▶ Prévia do Reel';render()};
function drafts(){try{return JSON.parse(localStorage.getItem('bdi-studio-drafts')||'[]')}catch{return[]}}
async function save(){const cover=await drawSlide(state.slides[0],0,true),list=drafts();list.unshift({id:Date.now(),createdAt:new Date().toISOString(),format:state.format,title:state.slides[0].headline,thumb:cover.toDataURL('image/jpeg',.72),project:JSON.parse(JSON.stringify(state)),caption:$('caption').value});try{localStorage.setItem('bdi-studio-drafts',JSON.stringify(list.slice(0,9)))}catch{return toast('Rascunho grande demais. Reduza a imagem de fundo.')}renderFeed();toast('Rascunho salvo no seu computador')}
$('saveProject').onclick=save;
function queueLabel(item){if(item.status==='publicado')return '✓ publicado';if(item.status==='erro-publicacao')return 'erro ao publicar';if(['enviando-midia','acionando-instagram','publicando-instagram'].includes(item.status))return 'publicando…';if(item.status==='aprovado-local')return '✓ aprovado';return item.format==='reel'?(item.hasVideo?'reel pronto':'vídeo pendente'):'fila local'}
async function openQueuedProject(id){try{const response=await fetch(`/api/queue/${id}/project`),item=await response.json();if(!response.ok)throw new Error(item.error||'Projeto não encontrado');state=item.project;lastQueuedId=id;pendingQueueVideo=null;recoverQueueVideo=state.format==='reel'&&!item.hasVideo;$('caption').value=item.caption||'';$('formatSelect').value=state.format;const mediaReady=state.format!=='reel'||item.hasVideo;$('approvePost').disabled=!mediaReady||item.status!=='fila-local';$('publishInstagram').disabled=item.status!=='aprovado-local'&&item.status!=='erro-publicacao';$('queuePost').textContent=recoverQueueVideo?'Gerar e anexar vídeo pendente':'Enviar à fila local do bot';$('approvalStatus').textContent=mediaReady?'Projeto recuperado da fila. Você pode revisar e aprovar.':'Projeto recuperado. Gere novamente somente o vídeo pendente.';syncFields();render();toast('Projeto da fila aberto')}catch(error){toast(error.message)}}
async function renderFeed(){const grid=$('feedGrid'),items=drafts();let published=[],queued=[];try{const [posts,queue]=await Promise.all([fetch('/api/posts'),fetch('/api/queue')]);if(posts.ok)published=(await posts.json()).slice(0,9);if(queue.ok)queued=(await queue.json()).slice(0,9)}catch{}const html=items.map(x=>`<button class="feeditem" data-draft="${x.id}" title="Abrir rascunho"><img src="${x.thumb}" alt=""><em>${x.format==='reel'?'reel salvo':'rascunho'}</em></button>`).join('')+queued.map(x=>`<button class="feeditem" data-queue="${x.id}" title="Abrir projeto da fila"><img src="${escapeHtml(x.cover)}" alt=""><em>${queueLabel(x)}</em></button>`).join('')+published.filter(x=>x.imagemFeed).map(x=>`<div class="feeditem"><img src="${x.imagemFeed}" alt=""><em>${escapeHtml(x.tipo||'post')}</em></div>`).join('');grid.innerHTML=html||'<div class="empty">Salve o primeiro rascunho para vê-lo no perfil.</div>';document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{const d=drafts().find(x=>x.id==b.dataset.draft);if(!d)return;state=d.project;$('caption').value=d.caption||'';$('formatSelect').value=state.format;syncFields();render();toast('Rascunho aberto')});document.querySelectorAll('[data-queue]').forEach(button=>button.onclick=()=>openQueuedProject(button.dataset.queue))}
$('clearDrafts').onclick=()=>{if(confirm('Apagar todos os rascunhos salvos neste navegador?')){localStorage.removeItem('bdi-studio-drafts');renderFeed()}};
$('preparePost').onclick=async()=>{await save();if(state.format==='reel')await exportReel();else await exportAll();try{await navigator.clipboard.writeText($('caption').value);toast(`${state.format==='reel'?'Vídeo':'Imagens'} e legenda preparados`)}catch{toast('Arquivo baixado; copie a legenda ao lado')}};
async function uploadQueueVideo(id,video,attempts=3){let lastError=null;for(let attempt=1;attempt<=attempts;attempt++){try{const response=await fetch(`/api/queue/${id}/video`,{method:'POST',headers:{'content-type':video.type||'video/webm'},body:video}),result=await response.json().catch(()=>({}));if(response.ok)return result;lastError=new Error(result.error||`Falha HTTP ${response.status}`)}catch(error){lastError=error}if(attempt<attempts)await wait(attempt*1200)}throw lastError||new Error('Não foi possível anexar o vídeo')}
async function finishPendingVideo(button){if(!pendingQueueVideo||!lastQueuedId)return false;button.disabled=true;button.textContent='Reenviando vídeo…';try{await uploadQueueVideo(lastQueuedId,pendingQueueVideo);pendingQueueVideo=null;$('approvePost').disabled=false;$('approvalStatus').textContent='Vídeo confirmado na fila. Revise a prévia e aprove quando estiver satisfeito.';button.textContent='Enviar à fila local do bot';await renderFeed();toast('Vídeo anexado com sucesso');return true}catch(error){button.textContent='Reenviar vídeo à fila';$('approvalStatus').textContent='Os slides foram salvos, mas o vídeo ainda não. Clique em “Reenviar vídeo à fila”.';toast(error.message||'O envio do vídeo falhou novamente');return false}finally{button.disabled=false}}
$('queuePost').onclick=async()=>{
  const button=$('queuePost'),images=[];if(pendingQueueVideo)return finishPendingVideo(button);if(recoverQueueVideo&&lastQueuedId){button.disabled=true;button.textContent='Gravando vídeo pendente…';try{pendingQueueVideo=await createReelBlob();recoverQueueVideo=false;return await finishPendingVideo(button)}catch(error){button.disabled=false;button.textContent='Gerar e anexar vídeo pendente';return toast(error.message||'Não foi possível recriar o vídeo')}}button.disabled=true;button.textContent=state.format==='reel'?'Gravando Reel…':'Preparando arquivos…';
  try{
    const video=state.format==='reel'?await createReelBlob():null;
    for(let i=0;i<state.slides.length;i++){const canvas=await drawSlide(state.slides[i],i);images.push(canvas.toDataURL('image/png'))}
    const response=await fetch('/api/queue',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project:state,caption:$('caption').value,images})});
    if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Não foi possível salvar na fila');
    const result=await response.json();lastQueuedId=result.id;if(video){pendingQueueVideo=video;button.textContent='Salvando vídeo…';if(!await finishPendingVideo(button))return}else $('approvePost').disabled=false;$('approvalStatus').textContent='Projeto completo na fila. Revise a prévia e aprove quando estiver satisfeito.';
    await renderFeed();toast(state.format==='reel'?'Reel completo salvo na fila local':'Criação salva na fila local do bot');
  }catch(error){toast(error.message||'Erro ao salvar na fila local')}finally{button.disabled=false;if(!pendingQueueVideo)button.textContent='Enviar à fila local do bot'}
};
$('approvePost').onclick=async()=>{if(!lastQueuedId)return toast('Envie o projeto à fila antes de aprovar');if(!confirm('Aprovar este projeto? Depois disso, o botão de publicação no Instagram será liberado.'))return;const button=$('approvePost');button.disabled=true;try{const response=await fetch(`/api/queue/${lastQueuedId}/approve`,{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível aprovar');button.textContent='✓ Projeto aprovado';button.classList.add('approved');$('publishInstagram').disabled=false;$('approvalStatus').textContent='Aprovado. Clique em “Publicar no Instagram” quando quiser enviar de verdade.';await renderFeed();toast('Projeto aprovado para publicação')}catch(error){button.disabled=false;toast(error.message)}};
async function pollPublication(){if(!lastQueuedId)return;try{const response=await fetch('/api/queue'),items=await response.json(),item=items.find(entry=>entry.id===lastQueuedId);if(!item)return;const button=$('publishInstagram');if(item.status==='publicado'){clearInterval(publishPoll);button.disabled=true;button.textContent='✓ Publicado no Instagram';button.className='publish-instagram wide published';$('approvalStatus').textContent=`Publicado com sucesso${item.instagramPostId?` • ID ${item.instagramPostId}`:''}.`;await renderFeed();toast('Reel publicado no Instagram')}else if(item.status==='erro-publicacao'){clearInterval(publishPoll);button.disabled=false;button.textContent='Tentar publicar novamente';button.className='publish-instagram wide';$('approvalStatus').textContent=item.publicationError||'A publicação falhou. Você pode tentar novamente.';await renderFeed()}else{$('approvalStatus').textContent=item.status==='enviando-midia'?'Enviando o vídeo para a área pública…':item.status==='acionando-instagram'?'Acionando a publicação protegida…':'O Instagram está processando o Reel…'}}catch{}}
$('publishInstagram').onclick=async()=>{if(!lastQueuedId)return toast('Nenhum projeto aprovado');if(!confirm(`Publicar este ${state.format} agora no Instagram? Esta ação é real e ficará visível no perfil.`))return;const button=$('publishInstagram');button.disabled=true;button.textContent='Iniciando publicação…';button.classList.add('publishing');try{const response=await fetch(`/api/queue/${lastQueuedId}/publish`,{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível iniciar a publicação');$('approvalStatus').textContent='Enviando a mídia para publicação…';clearInterval(publishPoll);publishPoll=setInterval(pollPublication,3000);await pollPublication()}catch(error){button.disabled=false;button.textContent='Publicar no Instagram';button.classList.remove('publishing');toast(error.message)}};
$('focusFeed').onclick=()=>{$('rightPanel').scrollIntoView({behavior:'smooth'})};
document.querySelectorAll('[data-mobile]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mobile]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('.left').style.display=b.dataset.mobile==='editor'?'block':'none';document.querySelector('.right').style.display=b.dataset.mobile==='publish'?'block':'none';document.querySelector('.stage').style.display=b.dataset.mobile==='preview'?'flex':'none'});
function importNewsSeed(){
  let seed;try{seed=JSON.parse(localStorage.getItem('bdi-news-seed')||'null')}catch{}if(!seed?.item)return;localStorage.removeItem('bdi-news-seed');if(seed.project){applySharedProject(seed.project);toast('Pauta criada com o Studio Engine compartilhado');return}const news=seed.item,source=news.fonte||'Fonte original',blocks=Array.isArray(news.blocos)?news.blocos.filter(Boolean):[],summary=blocks[0]||news.descricao||'Consulte a matéria original e complete o contexto antes de publicar.',articleContext=blocks[1]||'',articleDetail=blocks[2]||'',category=(news.pilares?.[0]||'Mercado agora').replace(/^./,letter=>letter.toUpperCase()),base={...defaultSlide(),source:''};
  const pillar=String(news.pilares?.[0]||'macro'),impactByPillar={cripto:'A notícia pode alterar a percepção de risco e a volatilidade dos criptoativos nas próximas horas.',bolsa:'O movimento pode influenciar expectativas para empresas, setores e o desempenho da Bolsa brasileira.',exterior:'O cenário externo afeta dólar, juros e o apetite por risco nos mercados brasileiros.',renda_fixa:'Mudanças nas expectativas de juros alteram preços, taxas e oportunidades na renda fixa.',fiis:'Juros, inflação e atividade econômica influenciam rendimentos e preços dos fundos imobiliários.',macro:'O dado ajuda a formar expectativas para inflação, juros, câmbio e atividade econômica.'},impact=impactByPillar[pillar]||impactByPillar.macro,radarByPillar={cripto:'Acompanhe preço, volume, regulação e a reação dos principais criptoativos.',bolsa:'Observe o comportamento do índice, dos setores envolvidos e do fluxo estrangeiro.',exterior:'Monitore bolsas globais, dólar, juros americanos e commodities.',renda_fixa:'Compare a curva de juros, inflação esperada e as taxas dos títulos.',fiis:'Observe juros futuros, vacância, rendimentos e comunicados dos fundos.',macro:'Os próximos indicadores e decisões de política econômica confirmarão ou limitarão esse movimento.'},radar=radarByPillar[pillar]||radarByPillar.macro;
  if(seed.format==='reel')state={format:'reel',active:0,originNews:{title:news.titulo,link:news.link,source},slides:[{...base,category:'Notícia em destaque',headline:news.titulo,body:summary,cta:'Continue assistindo',duration:4},{...base,category:'O que aconteceu',headline:'O fato por trás da manchete',body:articleContext||summary,cta:'Veja por que importa',duration:5},{...base,category:'Por que importa',headline:'O impacto para o investidor',body:articleDetail||impact,cta:'Continue para o radar',duration:5},{...base,category:'No radar',headline:'O que acompanhar a partir de agora',body:blocks[3]||radar,cta:'Salve este Reel',duration:5},{...base,category:'Fonte',headline:`Informação publicada por ${source}`,body:'Consulte a matéria original para acompanhar atualizações e o contexto completo.',cta:'Conteúdo informativo',duration:3}]};
  else state={format:'carousel',active:0,originNews:{title:news.titulo,link:news.link,source},slides:[{...base,category,headline:news.titulo,body:summary,cta:'Arraste para entender →'},{...base,category:'O que aconteceu',headline:'O fato por trás da manchete',body:summary,cta:'Veja por que importa →'},{...base,category:'Contexto',headline:'Por que o mercado está olhando para isso',body:impact,cta:'Entenda os efeitos →'},{...base,category:'Impacto',headline:'O que muda para o investidor',body:impact,cta:'Veja o que acompanhar →'},{...base,category:'No radar',headline:'Os próximos sinais importantes',body:radar,cta:'Confira a fonte →'},{...base,category:'Fonte',headline:`Informação publicada por ${source}`,body:'Acompanhe a matéria original para atualizações e contexto completo.',cta:'Salve este resumo'}]};
  state.slides.forEach((slide,index)=>{if(news.link){slide.image=articleMediaUrl(news.link,index);slide.imageCredit=`Crédito da imagem: ${source}`}slide.source=index===state.slides.length-1?`Fonte das informações: ${source}`:''});$('caption').value=`${news.titulo}\n\n${summary}\n\nFonte das informações: ${source}\n${news.link||''}\n\nImagens: confira a licença e o crédito autoral antes de publicar.\n\nConteúdo informativo; não é recomendação de investimento.\n\n#mercadofinanceiro #investimentos #bomdiainvestidor`;$('formatSelect').value=state.format;syncFields();toast(`Pauta importada como ${seed.format==='reel'?'Reel':'carrossel'}`);
}
function applySharedProject(shared){
  const format=['feed','story','carousel','reel'].includes(shared.format)?shared.format:'feed',fallback=defaultSlide();
  if(!Array.isArray(shared.slides)||!shared.slides.length||shared.slides.length>20)throw new Error();
  const cleanText=(input,max)=>String(input||'').slice(0,max),cleanColor=(input,standard)=>/^#[0-9a-f]{6}$/i.test(String(input))?input:standard,originLink=shared.originNews?.link||'',originSource=cleanText(shared.originNews?.source||'Fonte original',60);
  state={format,active:0,originNews:shared.originNews||null,slides:shared.slides.map((slide,index)=>{const supplied=String(slide.image||''),articleImage=!supplied&&Boolean(originLink),image=supplied.startsWith('data:image/')||supplied.startsWith('/api/news/media?')?supplied:articleMediaUrl(originLink,index);return{category:cleanText(slide.category,28),headline:cleanText(slide.headline,150),body:cleanText(slide.body,300),source:cleanText(slide.source||(originLink?`Fonte: ${originSource}`:''),80),imageCredit:cleanText(slide.imageCredit||(articleImage?`Crédito da imagem: ${originSource}`:''),80),cta:cleanText(slide.cta,55),colorA:cleanColor(slide.colorA,fallback.colorA),colorB:cleanColor(slide.colorB,fallback.colorB),accent:cleanColor(slide.accent,fallback.accent),image,duration:Math.min(10,Math.max(1,Number(slide.duration)||3))}})};
  $('caption').value=cleanText(shared.caption,2200);$('formatSelect').value=format;syncFields();render();return true
}
function importSharedProject(){
  const encoded=new URLSearchParams(location.search).get('projeto');if(!encoded)return false;
  try{let value=encoded.replace(/-/g,'+').replace(/_/g,'/');while(value.length%4)value+='=';applySharedProject(JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(value),char=>char.charCodeAt(0)))));toast('Reel personalizado carregado');return true}catch{toast('Não foi possível importar este projeto');return false}
}
async function importProjectFile(){const id=new URLSearchParams(location.search).get('arquivo');if(!id)return false;if(!/^[a-z0-9-]{1,80}$/.test(id)){toast('Projeto local inválido');return false}try{const response=await fetch(`/projetos-studio/${id}.json`);if(!response.ok)throw new Error();applySharedProject(await response.json());toast('Reel local carregado com 6 cenas');return true}catch{toast('O arquivo do projeto não foi encontrado');return false}}
importNewsSeed();
importSharedProject();
syncFields();render();renderFeed();
importProjectFile();
